name: Run pyright
on: [push, pull_request]


jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Install Dependencies
        run: poetry install
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: ./.github/workflows/setup
      - name: Run pyright
        run: poetry run pyright
